### ISSUE TITLE
'install-app-deps' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by liudonghua123** [skwid138/electron-create-react-app#1]
When I execute `npm i` or `yarn`, it always gave me `'install-app-deps' is not recognized as an internal or external command` error.

After some debugging, I found that you were missing `electron-builder` in `devDependencies` of `package.json`, so try to install it with `npm i -D electron-builder`.

**Comment by skwid138** [comment]
@liudonghua123 - I really appreciate the help. I don't see the install-app-deps or electron-builder directories in node-modules in the original local repo, but something must have done that in the process of making creating this. I've updated the dev dependencies accordingly. Thanks again for the help.
